os: osx
osx_image: xcode9.4
language: swift
script: xcodebuild clean build test -workspace FFTopNotification.xcworkspace -scheme FFTopNotification_Tests -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.2,name=iPhone XÊ€" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
