os: osx
osx_image: xcode9.4
language: swift
script: xcodebuild clean build test -workspace Example/FFTopNotification.xcworkspace -scheme FFTopNotification_Tests -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.4,name=iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
